# Generated by Django 4.2.1 on 2023-08-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('field', models.CharField(max_length=250, verbose_name='field')),
                ('comment', models.TextField(verbose_name='comment')),
                ('like', models.IntegerField(default=0, verbose_name='score')),
                ('img', models.ImageField(upload_to='public/images/home/headers', verbose_name='img')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('img', models.ImageField(upload_to='public/images/home/headers', verbose_name='img')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('img', models.ImageField(upload_to='public/images/home/publicSolution', verbose_name='img')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
            ],
        ),
    ]
