# Generated by Django 4.2.1 on 2023-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, verbose_name='link')),
                ('img', models.ImageField(upload_to='public/images/home/social', verbose_name='image')),
            ],
        ),
    ]
