# Generated by Django 4.2.1 on 2023-08-15 09:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.TextField(null=True, verbose_name='short_description')),
                ('img', models.ImageField(null=True, upload_to='public/images/blogs/blog', verbose_name='img')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
