# Generated by Django 3.2.8 on 2023-09-15 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
