# Generated by Django 3.2.8 on 2023-09-15 06:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.TextField(null=True, verbose_name='short_description')),
                ('img', models.ImageField(null=True, upload_to='public/images/services/service', verbose_name='img')),
                ('feature', ckeditor.fields.RichTextField()),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='service_id')),
            ],
        ),
    ]
