# Generated by Django 3.2.8 on 2023-09-15 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('service', '0003_auto_20230915_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='industry',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='industry.industry'),
        ),
    ]
