# Generated by Django 3.2.8 on 2023-09-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('service', '0004_service_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='industry.industry'),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
