# Generated by Django 3.2.8 on 2023-11-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20230918_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaile',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.product'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=200, null=True, verbose_name='icon'),
        ),
    ]
