# Generated by Django 3.2.8 on 2023-12-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20231109_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaile',
            name='svg',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
        migrations.AddField(
            model_name='detaile',
            name='icon',
            field=models.CharField(default='<i></i>', max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
