# Generated by Django 3.2.8 on 2023-12-03 06:07

from django.db import migrations, models
import django.db.models.deletion
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20231203_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaile',
            name='icon',
            field=faicon.fields.FAIconField(max_length=50),
        ),
        migrations.CreateModel(
            name='OurFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('icon', faicon.fields.FAIconField(max_length=50)),
                ('service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
