# Generated by Django 3.2.8 on 2023-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaile',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ourfeature',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
