# Generated by Django 3.2.8 on 2023-09-15 12:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0002_alter_industry_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(null=True, upload_to='public/images/industries/industries', verbose_name='banner')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industry.industry')),
            ],
        ),
    ]
