# Generated by Django 3.2.8 on 2023-09-18 05:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='img',
        ),
        migrations.AddField(
            model_name='solution',
            name='long_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Long Description'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='public/images/industries/industries', verbose_name='banner')),
                ('alt', models.CharField(max_length=200, verbose_name='alt')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=250, verbose_name='name')),
                ('solution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.solution')),
            ],
        ),
    ]
