# Generated by Django 3.2.8 on 2023-11-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_alter_solution_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='img',
            field=models.ImageField(null=True, upload_to='public/images/solution/solutions', verbose_name='banner'),
        ),
    ]
